### ISSUE TITLE
Clarification needed on index creation 

### ISSUE THREAD

**Issue by erikswed** [firebase/friendlyeats-android#3]
Thanks for the Code lab.
In step 5  "Sort and filter data" user learns to create an index in the Firestore. The index talked about is `price `and `numRating`. However there is no explanation why in the demo app user can  filer on food and  city without creating this Firestore index?

Further explanation:
If I search for city Miami I get two hits. This does not require a Firestore index right.
There are two Miami one with coffee and one with pizza.
If I search for city Miami and food pizza I get one result.  This should require a Firestore index or??

**Comment by samtstern** [comment]
@erikswed the behavior you're seeing likely has to do with our offline behavior.  When reading data, we can return some documents from the offline cache even without the proper indexes.  So since you created all the restaurants on this same device, you get seemingly impossible results when querying.

If use another device or just uninstall and reinstall the app, you'll see that those queries fail due to lack of index as expected.

**Comment by erikswed** [comment]
Thanks yea that makes sense . I see now the setPersistenceEnabled is enabled by default in Firestore I was thinking it was not

**Comment by samtstern** [comment]
@erikswed yes we enable persistence by default on Android and iOS, but not on Web.

Thanks for doing the codelab!  I am going to close this issue since it's working fine and I purposely didn't mention this in the text, but let me know if you think additional clarification is needed.
