### ISSUE TITLE
Warning on import about the build cache

### ISSUE THREAD

**Issue by samtstern** [firebase/friendlyeats-android#30]
```
WARNING: The option setting 'android.enableBuildCache=false' is experimental and unsupported.
The current default is 'true'.
Affected Modules: app
```

**Comment by rosariopfernandes** [comment]
That's because build cache is disabled on the [gradle.properties](https://github.com/firebase/friendlyeats-android/blob/master/gradle.properties) file:
```properties
android.enableBuildCache=false
```

Now I don't understand why was it disabled in first place, but removing that line clears the warning and actually [speeds up the build](https://developer.android.com/studio/build/build-cache#disable_build_cache) (also tried on a local instance).

**Comment by samtstern** [comment]
@rosariopfernandes yep I put that there on purpose because when I was working on this app and testing out `SNAPSHOT` builds of the Firestore SDK the build cache was messing with me.  I filed this issue as a reminder to myself, I will remove that line now.
