### ISSUE TITLE
Limit to 1 review per user?

### ISSUE THREAD

**Issue by langhimebaugh** [firebase/friendlyeats-android#37]
Not really a bug, but maybe a logical bug.
Logic allows for unlimited review submissions.
Would be nice to limit to 1 review per user.
I enjoyed this codelab!

**Comment by samtstern** [comment]
@langhimebaugh thanks for the feedback!  I agree that in a "real" app you'd definitely want this.  However for testing purposes it makes it easier to be able to submit multiple reviews so that you can see the list fill up and watch the "average score" change without having to log out and back in.

Glad you enjoyed the codelab!
