### ISSUE TITLE
Question about the FirestoreAdapter DocumentSnapshot deserialized

### ISSUE THREAD

**Issue by erikswed** [firebase/friendlyeats-android#4]
Thanks for the codelab its fun to learn this coming from Firebase real time databas.

In the `FirestoreAdapter ` class javadoc I read:
```
/**
 * RecyclerView adapter for displaying the results of a Firestore {@link Query}.
 *
 * Note that this class forgoes some efficiency to gain simplicity. For example, the result of
 * {@link DocumentSnapshot#toObject(Class)} is not cached so the same object may be deserialized
 * many times as the user scrolls.
 */
```
First I was thinking that efficiency explanation should be in the  `RestaurantAdapter` but could you explain  some more how this works if this is some Cloud Firestore feature or RecyclerView? 

What about that all objects are cashed on Android and never read twice unless they are changed? What does this mean "many times as the user scrolls." scroll happens in `RestaurantAdapter` which read the already loaded `DocumentSnapshot`´s objects or??

**Comment by samtstern** [comment]
@erikswed thanks for the feedback.  Calling `.toObject()` uses reflection to turn the `DocumentShapshot` into your own custom model class.  If you call `toObject` on the same snapshot a few times, this same somewhat expensive operation is done each time even though it would be more efficient to save the result of `toObject()` somewhere rather than recreating it each time you need it.

The adapter in this codelab is a simple one that is useful for learning about Firestore.  If you want to use the most efficient Firestore RecyclerView adapter implementation, try the one we built in FirebaseUI:
https://github.com/firebase/firebaseui-android

**Comment by erikswed** [comment]
Thanks grate info. What about in the Firebase real time databas like:
```
   @Override
    public void onDataChange(DataSnapshot dataSnapshot) {
        Post post = dataSnapshot.getValue(Post.class);
        System.out.println(post);
    }
```
Is this also an expensive operation like you describe?   What´s the differens under the hood?

**Comment by samtstern** [comment]
@erikswed when we say "Cloud Firestore caches data that you are using" we mean that the `DocumentSnapshot` is cached, so we don't contact the server again unless we have to or you ask us to.

What is not cached is the conversion from `DocumentSnapshot` to your custom object classes.  That operation is repeated each time you call `.toObject()`.
